name: test Marc

on:
  push:
    branches: [main]

jobs:
  list:
    runs-on: docker-ishimura
    steps:
      - uses: actions/checkout@v3
      - name: ls container docker-ishimura
        run: ls -ltha / 
      - name: hostname del docker-ishimura
        run: hostname